"""
Type-specific plots for the final Spectral Biclustering model.

The script does NOT refit the model. It reads the reports generated by
spectral_biclustering_pipeline.py and produces separate visualizations for:

1. Binary-feature block means.
2. Binary-feature block contrasts.
3. Numeric-feature block means.
4. Numeric-feature block contrasts.
5. Detailed binary and numeric profiles for one selected column cluster
   (C1 by default).
6. A CSV containing all features assigned to the selected column cluster.

Interpretation
--------------
For binary features, a block mean is the fraction of values equal to 1.
For numeric features, a block mean is the average normalized value.

A type-specific contrast is computed as:

    block type-specific mean
    - global type-specific mean of the same column cluster

Therefore, binary and numeric values are never mixed in the same contrast.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

import matplotlib.pyplot as plt
from matplotlib.colors import TwoSlopeNorm
import numpy as np
import pandas as pd


@dataclass(frozen=True)
class Config:
    """All paths and plotting options are defined here."""

    project_dir: Path = Path(__file__).resolve().parent
    final_report_dir: Path | None = None
    output_dir: Path | None = None

    focus_column_cluster: int = 1
    contrast_annotation_threshold: float = 0.03
    dpi: int = 300

    def resolved_final_report_dir(self) -> Path:
        if self.final_report_dir is not None:
            return self.final_report_dir
        return (
            self.project_dir
            / "reports"
            / "spectral_biclustering_pipeline"
            / "03_final_model"
        )

    def resolved_output_dir(self) -> Path:
        if self.output_dir is not None:
            return self.output_dir
        return self.resolved_final_report_dir() / "type_specific_plots"


CONFIG = Config()


REQUIRED_BLOCK_COLUMNS = {
    "row_cluster",
    "column_cluster",
    "n_binary_features",
    "n_numeric_features",
    "binary_n_values",
    "binary_mean",
    "numeric_n_values",
    "numeric_mean",
}


def read_csv_checked(path: Path, required_columns: set[str]) -> pd.DataFrame:
    """Read a CSV and verify that all required columns are present."""
    if not path.exists():
        raise FileNotFoundError(f"Required file not found: {path}")

    frame = pd.read_csv(path)
    missing = required_columns.difference(frame.columns)
    if missing:
        raise ValueError(
            f"File {path.name} is missing columns: {sorted(missing)}"
        )
    return frame


def load_reports(config: Config) -> tuple[pd.DataFrame, ...]:
    """Load final-model reports generated by the main pipeline."""
    report_dir = config.resolved_final_report_dir()

    blocks = read_csv_checked(
        report_dir / "block_statistics.csv",
        REQUIRED_BLOCK_COLUMNS,
    )
    rows = read_csv_checked(
        report_dir / "row_cluster_summary.csv",
        {
            "row_cluster",
            "n_rows",
            "target_1_fraction",
        },
    )
    columns = read_csv_checked(
        report_dir / "column_cluster_summary.csv",
        {
            "column_cluster",
            "n_features",
            "n_binary_features",
            "n_numeric_features",
        },
    )
    assignments = read_csv_checked(
        report_dir / "column_assignments.csv",
        {
            "feature",
            "feature_type",
            "zero_fraction",
            "column_cluster",
        },
    )

    return blocks, rows, columns, assignments


def validate_complete_block_grid(blocks: pd.DataFrame) -> None:
    """Ensure that the block report contains every row-column combination."""
    n_rows = blocks["row_cluster"].nunique()
    n_columns = blocks["column_cluster"].nunique()
    expected = n_rows * n_columns
    observed = blocks[["row_cluster", "column_cluster"]].drop_duplicates().shape[0]

    if observed != expected:
        raise ValueError(
            "block_statistics.csv does not contain the complete block grid: "
            f"expected {expected} blocks, found {observed}."
        )


def weighted_cluster_mean(
    group: pd.DataFrame,
    value_column: str,
    weight_column: str,
) -> float:
    """Compute a weighted mean, ignoring blocks without that feature type."""
    valid = group[value_column].notna() & (group[weight_column] > 0)
    if not valid.any():
        return np.nan

    values = group.loc[valid, value_column].to_numpy(dtype=float)
    weights = group.loc[valid, weight_column].to_numpy(dtype=float)
    return float(np.average(values, weights=weights))


def add_type_specific_contrasts(blocks: pd.DataFrame) -> pd.DataFrame:
    """Add separate binary and numeric reference means and contrasts."""
    enriched = blocks.copy()

    binary_global = (
        enriched.groupby("column_cluster", sort=True)
        .apply(
            weighted_cluster_mean,
            value_column="binary_mean",
            weight_column="binary_n_values",
            include_groups=False,
        )
        .rename("binary_column_cluster_global_mean")
    )

    numeric_global = (
        enriched.groupby("column_cluster", sort=True)
        .apply(
            weighted_cluster_mean,
            value_column="numeric_mean",
            weight_column="numeric_n_values",
            include_groups=False,
        )
        .rename("numeric_column_cluster_global_mean")
    )

    enriched = enriched.merge(
        binary_global,
        left_on="column_cluster",
        right_index=True,
        how="left",
    )
    enriched = enriched.merge(
        numeric_global,
        left_on="column_cluster",
        right_index=True,
        how="left",
    )

    enriched["binary_contrast"] = (
        enriched["binary_mean"]
        - enriched["binary_column_cluster_global_mean"]
    )
    enriched["numeric_contrast"] = (
        enriched["numeric_mean"]
        - enriched["numeric_column_cluster_global_mean"]
    )

    return enriched


def row_label_map(rows: pd.DataFrame) -> dict[int, str]:
    """Create informative labels for row clusters."""
    labels: dict[int, str] = {}
    for row in rows.itertuples(index=False):
        labels[int(row.row_cluster)] = (
            f"R{int(row.row_cluster)}\n"
            f"n={int(row.n_rows)}\n"
            f"Activity 1={100 * float(row.target_1_fraction):.1f}%"
        )
    return labels


def column_label_map(
    columns: pd.DataFrame,
    feature_type: str,
) -> dict[int, str]:
    """Create labels reporting the relevant feature count in each cluster."""
    count_column = (
        "n_binary_features"
        if feature_type == "binary"
        else "n_numeric_features"
    )
    short_name = "bin" if feature_type == "binary" else "num"

    labels: dict[int, str] = {}
    for row in columns.itertuples(index=False):
        cluster = int(row.column_cluster)
        count = int(getattr(row, count_column))
        labels[cluster] = f"C{cluster}\n{short_name}={count}"
    return labels


def pivot_metric(
    blocks: pd.DataFrame,
    metric: str,
    valid_clusters: list[int],
) -> pd.DataFrame:
    """Create a row-cluster by column-cluster matrix for one metric."""
    matrix = (
        blocks.pivot(
            index="row_cluster",
            columns="column_cluster",
            values=metric,
        )
        .sort_index()
        .reindex(columns=valid_clusters)
    )
    return matrix


def plot_mean_heatmap(
    matrix: pd.DataFrame,
    row_labels: dict[int, str],
    column_labels: dict[int, str],
    title: str,
    colorbar_label: str,
    output_path: Path,
    dpi: int,
) -> None:
    """Plot direct type-specific means on their natural [0, 1] scale."""
    values = matrix.to_numpy(dtype=float)

    fig_width = max(9.0, 1.45 * matrix.shape[1] + 4.0)
    fig, ax = plt.subplots(figsize=(fig_width, 7.0))

    image = ax.imshow(
        values,
        aspect="auto",
        interpolation="nearest",
        cmap="YlGnBu",
        vmin=0.0,
        vmax=1.0,
    )

    ax.set_xticks(np.arange(matrix.shape[1]))
    ax.set_xticklabels(
        [column_labels[int(cluster)] for cluster in matrix.columns],
        fontsize=9,
    )
    ax.set_yticks(np.arange(matrix.shape[0]))
    ax.set_yticklabels(
        [row_labels[int(cluster)] for cluster in matrix.index],
        fontsize=9,
    )

    for i in range(matrix.shape[0]):
        for j in range(matrix.shape[1]):
            value = values[i, j]
            if np.isnan(value):
                continue
            ax.text(
                j,
                i,
                f"{value:.2f}",
                ha="center",
                va="center",
                fontsize=10,
                fontweight="bold",
            )

    colorbar = fig.colorbar(image, ax=ax, pad=0.02)
    colorbar.set_label(colorbar_label)

    ax.set_title(title, fontsize=15, pad=14)
    ax.set_xlabel("Cluster di feature")
    ax.set_ylabel("Cluster di molecole")

    fig.tight_layout()
    fig.savefig(output_path, dpi=dpi, bbox_inches="tight")
    plt.close(fig)


def plot_contrast_heatmap(
    matrix: pd.DataFrame,
    row_labels: dict[int, str],
    column_labels: dict[int, str],
    title: str,
    colorbar_label: str,
    output_path: Path,
    annotation_threshold: float,
    dpi: int,
) -> None:
    """Plot type-specific contrasts with a symmetric scale centred at zero."""
    values = matrix.to_numpy(dtype=float)
    finite_values = values[np.isfinite(values)]
    if finite_values.size == 0:
        return

    limit = float(np.max(np.abs(finite_values)))
    if limit == 0:
        limit = 1e-9

    fig_width = max(9.0, 1.45 * matrix.shape[1] + 4.0)
    fig, ax = plt.subplots(figsize=(fig_width, 7.0))

    image = ax.imshow(
        values,
        aspect="auto",
        interpolation="nearest",
        cmap="RdBu_r",
        norm=TwoSlopeNorm(vmin=-limit, vcenter=0.0, vmax=limit),
    )

    ax.set_xticks(np.arange(matrix.shape[1]))
    ax.set_xticklabels(
        [column_labels[int(cluster)] for cluster in matrix.columns],
        fontsize=9,
    )
    ax.set_yticks(np.arange(matrix.shape[0]))
    ax.set_yticklabels(
        [row_labels[int(cluster)] for cluster in matrix.index],
        fontsize=9,
    )

    for i in range(matrix.shape[0]):
        for j in range(matrix.shape[1]):
            value = values[i, j]
            if np.isnan(value) or abs(value) < annotation_threshold:
                continue
            ax.text(
                j,
                i,
                f"{value:+.2f}",
                ha="center",
                va="center",
                fontsize=10,
                fontweight="bold" if abs(value) >= 0.15 else "normal",
            )

    colorbar = fig.colorbar(image, ax=ax, pad=0.02)
    colorbar.set_label(colorbar_label)

    ax.set_title(title, fontsize=15, pad=14)
    ax.set_xlabel("Cluster di feature")
    ax.set_ylabel("Cluster di molecole")

    fig.tight_layout()
    fig.savefig(output_path, dpi=dpi, bbox_inches="tight")
    plt.close(fig)


def plot_focus_cluster(
    blocks: pd.DataFrame,
    rows: pd.DataFrame,
    column_cluster: int,
    mean_column: str,
    global_mean_column: str,
    feature_type_label: str,
    ylabel: str,
    output_path: Path,
    dpi: int,
) -> None:
    """Plot one column cluster separately, with its global mean as reference."""
    subset = (
        blocks.loc[blocks["column_cluster"] == column_cluster]
        .sort_values("row_cluster")
        .copy()
    )

    if subset.empty or subset[mean_column].notna().sum() == 0:
        return

    row_info = rows.set_index("row_cluster")
    x_labels = [
        (
            f"R{int(cluster)}\n"
            f"n={int(row_info.loc[cluster, 'n_rows'])}\n"
            f"Act.1={100 * row_info.loc[cluster, 'target_1_fraction']:.1f}%"
        )
        for cluster in subset["row_cluster"]
    ]

    values = subset[mean_column].to_numpy(dtype=float)
    global_mean = float(subset[global_mean_column].dropna().iloc[0])

    fig, ax = plt.subplots(figsize=(8.5, 5.8))
    positions = np.arange(len(subset))
    bars = ax.bar(positions, values)

    ax.axhline(
        global_mean,
        linestyle="--",
        linewidth=1.5,
        label=f"Media globale C{column_cluster} = {global_mean:.3f}",
    )

    for bar, value in zip(bars, values, strict=True):
        if np.isnan(value):
            continue
        ax.text(
            bar.get_x() + bar.get_width() / 2,
            value + 0.015,
            f"{value:.3f}",
            ha="center",
            va="bottom",
            fontsize=10,
        )

    ax.set_xticks(positions)
    ax.set_xticklabels(x_labels)
    ax.set_ylim(0.0, min(1.05, max(1.0, np.nanmax(values) + 0.12)))
    ax.set_ylabel(ylabel)
    ax.set_xlabel("Cluster di molecole")
    ax.set_title(
        f"C{column_cluster}: profilo delle feature {feature_type_label}",
        fontsize=14,
    )
    ax.legend(frameon=False)

    fig.tight_layout()
    fig.savefig(output_path, dpi=dpi, bbox_inches="tight")
    plt.close(fig)


def export_focus_features(
    assignments: pd.DataFrame,
    column_cluster: int,
    output_path: Path,
) -> None:
    """Save the complete feature list assigned to the selected cluster."""
    focus = (
        assignments.loc[assignments["column_cluster"] == column_cluster]
        .sort_values(["feature_type", "zero_fraction", "feature"])
        .reset_index(drop=True)
    )
    focus.to_csv(output_path, index=False)


def main() -> None:
    config = CONFIG
    output_dir = config.resolved_output_dir()
    output_dir.mkdir(parents=True, exist_ok=True)

    blocks, rows, columns, assignments = load_reports(config)
    validate_complete_block_grid(blocks)
    blocks = add_type_specific_contrasts(blocks)

    row_labels = row_label_map(rows)

    binary_clusters = (
        columns.loc[columns["n_binary_features"] > 0, "column_cluster"]
        .astype(int)
        .sort_values()
        .tolist()
    )
    numeric_clusters = (
        columns.loc[columns["n_numeric_features"] > 0, "column_cluster"]
        .astype(int)
        .sort_values()
        .tolist()
    )

    binary_labels = column_label_map(columns, "binary")
    numeric_labels = column_label_map(columns, "numeric")

    binary_means = pivot_metric(blocks, "binary_mean", binary_clusters)
    binary_contrasts = pivot_metric(
        blocks, "binary_contrast", binary_clusters
    )
    numeric_means = pivot_metric(blocks, "numeric_mean", numeric_clusters)
    numeric_contrasts = pivot_metric(
        blocks, "numeric_contrast", numeric_clusters
    )

    plot_mean_heatmap(
        matrix=binary_means,
        row_labels=row_labels,
        column_labels=binary_labels,
        title="Feature binarie: frazione media di valori 1",
        colorbar_label="Frazione di valori 1",
        output_path=output_dir / "01_binary_block_means.png",
        dpi=config.dpi,
    )
    plot_contrast_heatmap(
        matrix=binary_contrasts,
        row_labels=row_labels,
        column_labels=binary_labels,
        title="Feature binarie: contrasto della frazione di valori 1",
        colorbar_label="Differenza dalla media binaria del cluster",
        output_path=output_dir / "02_binary_block_contrasts.png",
        annotation_threshold=config.contrast_annotation_threshold,
        dpi=config.dpi,
    )
    plot_mean_heatmap(
        matrix=numeric_means,
        row_labels=row_labels,
        column_labels=numeric_labels,
        title="Feature numeriche: valore normalizzato medio",
        colorbar_label="Valore normalizzato medio",
        output_path=output_dir / "03_numeric_block_means.png",
        dpi=config.dpi,
    )
    plot_contrast_heatmap(
        matrix=numeric_contrasts,
        row_labels=row_labels,
        column_labels=numeric_labels,
        title="Feature numeriche: contrasto del valore medio",
        colorbar_label="Differenza dalla media numerica del cluster",
        output_path=output_dir / "04_numeric_block_contrasts.png",
        annotation_threshold=config.contrast_annotation_threshold,
        dpi=config.dpi,
    )

    focus = config.focus_column_cluster
    plot_focus_cluster(
        blocks=blocks,
        rows=rows,
        column_cluster=focus,
        mean_column="binary_mean",
        global_mean_column="binary_column_cluster_global_mean",
        feature_type_label="binarie",
        ylabel="Frazione media di valori 1",
        output_path=output_dir / f"05_C{focus}_binary_profile.png",
        dpi=config.dpi,
    )
    plot_focus_cluster(
        blocks=blocks,
        rows=rows,
        column_cluster=focus,
        mean_column="numeric_mean",
        global_mean_column="numeric_column_cluster_global_mean",
        feature_type_label="numeriche",
        ylabel="Valore normalizzato medio",
        output_path=output_dir / f"06_C{focus}_numeric_profile.png",
        dpi=config.dpi,
    )

    export_focus_features(
        assignments=assignments,
        column_cluster=focus,
        output_path=output_dir / f"C{focus}_feature_list.csv",
    )

    output_columns = [
        "row_cluster",
        "column_cluster",
        "n_binary_features",
        "n_numeric_features",
        "binary_mean",
        "binary_column_cluster_global_mean",
        "binary_contrast",
        "numeric_mean",
        "numeric_column_cluster_global_mean",
        "numeric_contrast",
    ]
    blocks[output_columns].sort_values(
        ["column_cluster", "row_cluster"]
    ).to_csv(
        output_dir / "type_specific_block_statistics.csv",
        index=False,
    )

    print("Type-specific plots completed")
    print(f"Reports read from: {config.resolved_final_report_dir()}")
    print(f"Plots saved in:   {output_dir}")
    print(f"Focus cluster:    C{focus}")
    print(f"Binary clusters:  {binary_clusters}")
    print(f"Numeric clusters: {numeric_clusters}")


if __name__ == "__main__":
    main()
